INSERT INTO "Management".productos (nombre, precio, unidad, usuario_modifica, fecha_modifica, accion_realizada)
VALUES('ACACIA', 1500, 'gr', 'generico', now(), 'creacion'), 
('BOLDO', 1500, 'gr', 'generico', now(), 'creacion') ,
('SEN', 1500, 'gr', 'generico', now(), 'creacion') ,
('CANELA ESP', 1500, 'gr', 'generico', now(), 'creacion'),
('CALENDULA', 1500, 'gr', 'generico', now(), 'creacion') ,
('MENTA', 1500, 'gr', 'generico', now(), 'creacion') ,
('ANIS COMUN', 1500, 'gr', 'generico', now(), 'creacion') ,
('QUIEBRABARRIGO', 1500, 'gr', 'generico', now(), 'creacion') ,
('SALVIA', 1500, 'gr', 'generico', now(), 'creacion'),
('TORONJIL', 1500, 'gr', 'generico', now(), 'creacion') ,
('CIDRON', 1500, 'gr', 'generico', now(), 'creacion') ,
('LIMONARIA', 1500, 'gr', 'generico', now(), 'creacion') ,
('DIENTELEON', 1500, 'gr', 'generico', now(), 'creacion') ,
('COLACABALLO', 1500, 'gr', 'generico', now(), 'creacion'),
('HINOJO', 1500, 'gr', 'generico', now(), 'creacion') ,
('ENELDO', 1500, 'gr', 'generico', now(), 'creacion') ,
('QUINUA', 1500, 'gr', 'generico', now(), 'creacion') ,
('EUCALIPTO', 1500, 'gr', 'generico', now(), 'creacion') ,
('ALCACHOFA', 1500, 'gr', 'generico', now(), 'creacion'),
('HIERBABUENA', 1500, 'gr', 'generico', now(), 'creacion') ,
('OREGANO', 1500, 'gr', 'generico', now(), 'creacion') ,
('LAUREL', 1500, 'gr', 'generico', now(), 'creacion') ,
('ALBAHACA', 1500, 'gr', 'generico', now(), 'creacion'), 
('ROMERO', 1500, 'gr', 'generico', now(), 'creacion'),
('TOMILLO', 1500, 'gr', 'generico', now(), 'creacion'), 
('AJONJOLI', 1500, 'gr', 'generico', now(), 'creacion'), 
('CILANTRO', 1500, 'gr', 'generico', now(), 'creacion') ,
('CANELA MOLIDA', 1500, 'gr', 'generico', now(), 'creacion') ,
('CURCUMA', 1500, 'gr', 'generico', now(), 'creacion'),
('JENGIBRE', 1500, 'gr', 'generico', now(), 'creacion'), 
('COMINO ENTERO', 1500, 'gr', 'generico', now(), 'creacion') ,
('COMINO MOLIDO', 1500, 'gr', 'generico', now(), 'creacion') ,
('COMINOS', 1500, 'gr', 'generico', now(), 'creacion'),
('PIMIENTA DULCE', 1500, 'gr', 'generico', now(), 'creacion') ,
('PIMIENTA NEGRA', 1500, 'gr', 'generico', now(), 'creacion') ,
('PIMIENTA MOLIDA', 1500, 'gr', 'generico', now(), 'creacion') ,
('PIMIENTAS', 1500, 'gr', 'generico', now(), 'creacion'),
('AJI EN POLVO', 1500, 'gr', 'generico', now(), 'creacion') ,
('CHIA', 1500, 'gr', 'generico', now(), 'creacion') ,
('SEMILLA CHIA 150', 1500, 'gr', 'generico', now(), 'creacion') ,
('ACHIOTE', 1500, 'gr', 'generico', now(), 'creacion'),
('ACHIOTE MOL', 1500, 'gr', 'generico', now(), 'creacion') ,
('CURRY', 1500, 'gr', 'generico', now(), 'creacion') ,
('PIMIENTA CAYENA', 1500, 'gr', 'generico', now(), 'creacion') ,
('VALERIANA', 1500, 'gr', 'generico', now(), 'creacion'),
('ESTEVIA', 1500, 'gr', 'generico', now(), 'creacion') ,
('GINKGO BILOBA', 1500, 'gr', 'generico', now(), 'creacion') ,
('ANIS ESTRELLADO', 1500, 'gr', 'generico', now(), 'creacion'), 
('FLOR DE JAMAICA', 1500, 'gr', 'generico', now(), 'creacion'),
('MANZANILLA', 1500, 'gr', 'generico', now(), 'creacion') ,
('TE VERDE', 1500, 'gr', 'generico', now(), 'creacion') ,
('NUEZ MOSCADA E', 1500, 'gr', 'generico', now(), 'creacion') ,
('NUEZ MOSCADA M', 1500, 'gr', 'generico', now(), 'creacion'),
('SEMILLA DE AMAPOLA', 1500, 'gr', 'generico', now(), 'creacion') ,
('CLAVO DE OLOR', 1500, 'gr', 'generico', now(), 'creacion') ,
('MORINGA', 1500, 'gr', 'generico', now(), 'creacion') ,
('FINAS HIERBAS', 1500, 'gr', 'generico', now(), 'creacion'),
('GUASCA', 1500, 'gr', 'generico', now(), 'creacion') ,
('CARDAMOMO', 1500, 'gr', 'generico', now(), 'creacion') ,
('BICARBONATO', 1500, 'gr', 'generico', now(), 'creacion'), 
('AJO', 1500, 'gr', 'generico', now(), 'creacion') ,
('SALSINA', 1500, 'gr', 'generico', now(), 'creacion'),
('COLOR', 1500, 'gr', 'generico', now(), 'creacion') ,
('PAPRIKA', 1500, 'gr', 'generico', now(), 'creacion'), 
('SAL MARINA', 1500, 'gr', 'generico', now(), 'creacion') ,
('CEBOLLA M', 1500, 'gr', 'generico', now(), 'creacion') ,
('LINAZA ENTERA', 1500, 'gr', 'generico', now(), 'creacion'),
('LINAZA MOLIDA', 1500, 'gr', 'generico', now(), 'creacion') ,
('LINAZAS', 1500, 'gr', 'generico', now(), 'creacion') ,
('UVAS PASAS', 1500, 'gr', 'generico', now(), 'creacion') ,
('MANI SAL', 1500, 'gr', 'generico', now(), 'creacion'),
('MANI DULCE', 1500, 'gr', 'generico', now(), 'creacion') ,
('COCO RALLADO', 1500, 'gr', 'generico', now(), 'creacion'), 
('COLOR LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('SALSINA LB', 1500, 'gr', 'generico', now(), 'creacion'),
('ACHIOTE LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('AJO LB', 1500, 'gr', 'generico', now(), 'creacion'),
('CURCUMA LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('PIMIENTA LB', 1500, 'gr', 'generico', now(), 'creacion'),
('JAMAICA LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('CEBOLLA LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('PAPRIKA AHU LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('LAUREL MOL LB', 1500, 'gr', 'generico', now(), 'creacion'),
('FINAS H LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('UVA LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('PAPRIKA LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('CILANTRO LB', 1500, 'gr', 'generico', now(), 'creacion'),
('OREGANO LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('JENGIBRE LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('CLAVO OLOR LB', 1500, 'gr', 'generico', now(), 'creacion'), 
('ANIS ESTRELLA LB', 1500, 'gr', 'generico', now(), 'creacion'),
('CANELA MOL LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('PIMIENTA CAYENA LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('QUIEBRABARRIGO LB', 1500, 'gr', 'generico', now(), 'creacion'),
('BICARBONATO LB', 1500, 'gr', 'generico', now(), 'creacion') ,
('UVAS PASAS 250g', 1500, 'gr', 'generico', now(), 'creacion') ,
('COCO RALLADO 250g', 1500, 'gr', 'generico', now(), 'creacion'),
('COCO RALLADO 100g', 1500, 'gr', 'generico', now(), 'creacion') ,
('MANI NATURAL 250g', 1500, 'gr', 'generico', now(), 'creacion') ,
('MANI DULCE 250g', 1500, 'gr', 'generico', now(), 'creacion'),
('MORINGA LB', 1500, 'gr', 'generico', now(), 'creacion');